import React from 'react'

function RiderTermsAndConditions() {
  return (
    <div>
      <p>
      PRIVACY POLICY

This privacy policy (“Privacy Policy”) explains how we collect, use, share and protect personal information about the users of the Platforms (“you” or “User”). It applies to the websites and applications where it appears, including the sites, services, and applications for Pikkro Same Day Courier Services (“Pikkro”). By using our website, products or services, and the Platform, you consent to the collection, use, and sharing of your personal data as described in this privacy policy and confirm that you have read and understood our privacy policy. We have created this Privacy Policy to demonstrate our commitment to the protection of your privacy and your personal information. Your use of and access to the Platforms is subject to this Privacy Policy and our Terms and Conditions. Any capitalized term used but not defined in this Privacy Policy shall have the meaning attributed to it in the Terms and Conditions.
A condition of each User’s use and access to the Platforms is their acceptance of the Terms of Use, which also involves acceptance of the terms of this Privacy Policy. You agree to the practices and policies outlined in this Privacy Policy and you hereby consent to our collection, use and sharing of your information as described in this Privacy Policy.
This Privacy Policy is an electronic record between you and Pikkro under the Information Technology Act, 2000 together with the Rules framed from time to time.
For the purpose of this Privacy Policy, where the context so requires, the term:
(i) “Applications"/ “App" or “Pikkro App" means the computer applications accessible from a Device and enabling access to Pikkro Services and shall include website https://www.pikkro.in/ mobile applications named  Pikkro Same Day Courier Service for Android and iOS.
(ii) “Applicable Law" shall include all laws, statutes, ordinance, regulations, guidelines, policies, and other pronouncements having the effect of law of all or any applicable jurisdictions by state, municipality, court, tribunal, government, ministry, department, commission, arbitrator or board or such other body which has the force of law within the territory of India.
(iii) “Pikkro Services" mean Pikkro on-demand lead generation and related services that enable the Client to seek and receive on-demand requests for Courier Services from the Courier; such Pikkro Services include access to Pikkro’s App/Site and Pikkro’s software, payment services, and related support services systems, as may be updated or modified from time to time.
(iv) “Client" means an end Client, the adult individual, or the corporate entity represented by a duly authorized individual, authorized by Pikkro to use Pikkro Services for the purpose of obtaining Courier Services.
(v) “Content" shall include without limitation, data, text, written posts, comments, software, scripts, interactive features generated, graphics, images, photos, documents, audio, video, location, data, nearby places and all other forms of information or data.
(vi) “Courier" means the independent person registered in the Courier App, seeking for rendering the Courier Services.
(vii) “Courier App" means the mobile application provided by Pikkro that enables Courier to access Pikkro Services for the purpose of seeking, receiving, and fulfilling on-demand requests for Courier Services by the Client, as may be updated, or modified from time to time.
(viii) “Courier Services" means provision of courier delivery services to the Client via Pikkro Services in the Territory.
(ix) “Device" means the Client's or the Courier's Device, through which the Client or the Courier will access Pikkro Services; means a mobile device, computer/laptop owned or any other device owned or controlled by the Client or by the Courier: (a) that meets the specifications for mobile devices as set forth at https://www.pikkro.in/ and (b) on which the App has been installed as authorized by Pikkro for the purpose of obtaining Courier Services or providing the Courier Services that can allow the Client and to the Courier to have access to website of Pikkro i.e., https://www.pikkro.in/ 
(x) “Site" means https://www.pikkro.in/ providing access to Pikkro Services.
(xi) “Territory" means India in which the Client can request for delivery of goods.
(xii) “Third Party Privacy Policies" shall mean this Privacy Policy (as amended, modified or restated from time to time) read with the privacy policies of TSPs (as defined below).
(xiii) “TSPs" shall mean, third party service providers, as applicable, whose services are used in addition to or in conjunction with the Pikkro Services.
(xiv) “User Content" shall mean any Content that the User saves, submits, posts, displays, uploads, shares, transmits through the Pikkro Services, including but not limited to, images, photos, documents, and contact details saved therein by the User, profile information, and any other Content or information that User stores or makes available on the Site or App; and
(xv) “User" means any person who accepts this Privacy Policy and Pikkro's Terms.
1.Acceptance
1.1. By accessing, registering, browsing, uploading, posting, or otherwise using Pikkro Services or otherwise providing information on the Site/App/Сourier App, User agrees that their Personal Information (as defined below) shall be handled in accordance with this Privacy Policy.

1.2. By impliedly or expressly accepting this Privacy Policy, the User also agrees to have read and be bound by and accepts:
1.2.1. all of Pikkro 's policies (including but not limited to Terms as amended from time to time);
1.2.2. any plan limits, product disclaimers or other restrictions presented to User on the Site/App/Сourier App; and
1.2.3. any applicable Third Party Privacy Policies.
1.3. User acknowledges and agrees to the collection, retention, and use of the information the User discloses to Pikkro in accordance with this Privacy Policy, including but not limited to User's consent for sharing User information as per this Privacy Policy.
1.4. User also acknowledges and agrees that with respect to certain activities, the collection, transfer, storage, and processing of User information may be undertaken by trusted third party partners or affiliates or agents of Pikkro such as credit card processors, insurance companies, web hosting providers, communication services, and web analytic providers, to help facilitate Pikkro in providing certain functions.
1.5. Unless stated otherwise, this Privacy Policy applies to all information that is disclosed by the User on the Site/App/Сourier App (hereinafter “Platform").
2. Collection and storage of information 
2.1. The information (which shall also include data) provided by you to Pikkro or collected from you by Pikkro may consist of “personal information” and “non-personal information”. 
2.2. Personal information is information collected that can be used to uniquely identify or contact you. Personal information for the purposes of this privacy policy shall include, but not be limited to your name, address, contact number, e-mail address or other contact information, information regarding your transactions on the website, your financial information, internet protocol address, any other items of “sensitive personal data or information” as such term is defined under the information technology (reasonable security practices and procedures and sensitive personal data of information) rules, 2011 enacted under the information technology act, 2000, identification code of your communication device which you use to access the website or any other information that you provide during your registration process, if any, on the website. 
2.3. Such personal information may be collected in various ways including during the course of you registering as a user on the website, registering as a merchant on the website, availing certain services offered on the website. Such instances include but are not limited to participating in any online survey or contest or otherwise posting user reviews or otherwise doing business on the website. 

2.4. We may receive personal information about you from third parties, such as social media services, commercially available sources, and business partners. If you access website through a social media service or connect a service on website to a social media service, the information we collect may include your user name associated with that social media service, any information or content the social media service has the right to share with us, such as your profile picture, email address or friends list, and any information you have made public in connection with that social media service. When you access the website through social media services or when you connect website to social media services, you are authorizing Pikkro to collect, store, and use and retain such information and content in accordance with this privacy policy. 
2.5. Pikkro may also collect information other than personal information from you through the website when you visit and / or use the website. Such information may be stored in server logs. This non-personal information may include your geographic location, details of your telecom service provider or internet service provider, the type of  Browser (internet explorer, Firefox, opera, google chrome etc.), The operating system of your system, device and the website you last visited before visiting the website or the duration of your stay on the website is also stored in the session along with the date and time of your access. 
2.6. Non-personal information is collected in various ways such through the use of cookies. Pikkro may store temporary or permanent “cookies” on your computer. You can erase or choose to block these cookies from your computer. You can configure your computer’s browser to alert you when we attempt to send you a cookie with an option to accept or refuse the cookie. If you have turned cookies off, you may be prevented from using certain features of the website. 
2.7. Please do note that personal information and non-personal information may be treated differently as per this privacy policy. 
2.8. You hereby represent to Pikkro that: a) the information you provide from time to time is and shall be authentic, correct, current and updated and you have all the rights, permissions and consents as may be required to provide such information to Pikkro. B) your providing the information to Pikkro and Pikkro's consequent storage, collection, usage, transfer, access or processing of the same shall not be in violation of any third-party agreement, laws, charter documents, judgments, orders and decrees. 
2.9. Pikkro and its officers, directors, contractors, or agents shall not be responsible for the authenticity of the information that you or any other user provide to Pikkro. You shall indemnify and hold harmless Pikkro and its officers, directors, contractors, or agents and any third party relying on the information provided by you in the event you are in breach of this privacy policy including this provision and the immediately preceding provision above. 
2.10. Your information will primarily be stored in electronic form, however certain data can also be stored in physical form. We may store, collect, process, and use your data in countries other than Republic of India but under compliance with applicable laws. We may enter into agreements with third parties (in or outside of India) to store or process your information or data. These third parties may have their own security standards to safeguard your information or data and we will on a commercial reasonable basis require such third parties to adopt reasonable security standards to safeguard your information / data. 
2.11. When you download our app, we may collect information about you, using technology which is not apparent to you, for example using “cookies” and other similar technologies. Specifically, we may collect information about other third-party applications installed on your mobile phone. We may anonymize, de-identify or aggregate this information collected. For example, we may do this for the purposes of conducting analytics, for example the use and disclosure of anonymized data to determine preferences and patterns and for business improvement. 
3. Use of Personal Information 
Pikkro collects, uses, stores and processes your information for any purpose as may be permissible under applicable laws (including where the applicable law provides for such collection, usage, storage or processes in accordance with the consent of the user) and shall include the following: 
3.1.  to facilitate your use of the website. 
3.2. to respond to your inquiries or fulfil your requests for information about the various services ordered on the website. 
3.3. to process and complete the orders placed and is shared as needed to process and complete the orders. 
3.4. to ensure that orders have are successfully delivered on time, and to keep you informed on the status of your order. 
3.5. to provide you with information about services available on the website and to send you information, materials, and orders. 
3.6. to send you important information regarding the website, changes in terms and conditions, user agreements, and policies and/or other administrative information. 
3.7. to send you surveys and marketing communications. 
3.8. to personalize your experience on the website by presenting advertisements, services and orders tailored to your preferences. 
3.9.to help you address your problems incurred on the website including addressing any technical problems. 
3.10. if you avail yourself of any service from the website, to complete and fulfil the same. 
3.11.  to protect the integrity and for proper administering of the website. 
3.12. to conduct internal reviews and data analysis for the website. 
3.13. to improve the services and content on the website. 
3.14. to conducting academic research, surveys, analytical studies on various aspects including user behavior, user preferences etc. 
3.15.to respond to legal, judicial, quasi-judicial process and provide information to law enforcement agencies or in connection with an investigation on matters related to public safety, as permitted by law. 
3.16. to implement information security practices. 
3.17. to determine any security breaches, computer contaminant or computer virus. 
3.18. to investigate, prevent, or take action regarding illegal activities and suspected fraud.
3.19. to undertake forensics of the concerned computer resource as a part of investigation or internal audit. 
3.20. to process any job application, you may submit; 
3.21. to trace computer resources or any person who may have contravened, or is suspected of having or being likely to contravene, any provision of law including the Information technology act, 2000 that is likely to have an adverse impact on the services provided on any website or by Pikkro; and 
3.22. to enable a potential buyer or investor to evaluate the business of Pikkro. 
[individually and collectively referred to as (“Uses”)] you hereby agree and acknowledge that the information so collected is for lawful purpose connected with a function or activity of Pikkro or any person on its behalf, and the collection of information is necessary for the purposes. 
4. Review of information: 
4.1. You may review, correct, update, change or delete your personal or non-personal information, either through the login page on the website or the “view my profile” section on the mobile app (collectively referred to as “your account”). Once you log into your account, you will be able to access and update your personal or non-personal information. If your personal or non-personal information has been provided to us, upon our request, through means other than the website, then you may review, correct, update, change or delete your personal or non-personal information by contacting us at ________________. (insert mail id)

4.2. You can delete any part of your personal or non-personal information or request us to delete your any such personal or non-personal information and we will comply with such requests within a reasonable time unless we are required to keep certain information for legal purposes. 
4.3. Should you choose to delete your personal or non-personal information, or modify it in a way that is not verifiable by us, or leads to such personal or non-personal information being incorrect, we will be unable to provide you with any services through our website, and such a deletion or modification may be regarded as the you seeking to discontinue receipt of any services from us. 
4.4. We reserve the right to verify and authenticate your identity and your personal or non-personal information in order to ensure accurate delivery of our services. Access to or correction, updating or deletion of your personal or non-personal information may be denied or limited by us if it would violate another person’s rights and/or is not otherwise permitted by applicable law. 
5. Sharing and disclosure of your information 
5.1. You hereby unconditionally agree and permit that Pikkro may transfer, share, disclose or part with all or any of your information, within and outside of the Republic of India to third party service providers / partners / banks and financial institutions for one or more of the purposes or as may be required by applicable law. 
5.2. you acknowledge and agree that, to the extent permissible under applicable laws, it is adequate that when Pikkro transfers your information to any other entity within or outside your country of residence, Pikkro will place contractual obligations on the transferee which will oblige the transferee to adhere to the provisions of this privacy policy. 
5.3. Pikkro may share statistical data and other details (other than your personal information) without your express or implied consent to facilitates various programmes or initiatives launched by Pikkro, its affiliates, agents, third party service providers, partners or banks & financial institutions, from time to time. We may transfer/disclose/share information (other than your personal information) to those parties who support our business, such as providing technical infrastructure services, analyzing how our services are used, providing merchants services, facilitating payments, or conducting academic research and surveys. These affiliates and third-party service providers shall adhere to confidentiality obligations consistent with this privacy policy. Notwithstanding the above, we use other third parties such as a credit/debit card processing company, payment gateway, pre-paid cards etc. To enable you to make payments for availing services. When you sign up for these services, you may have the ability to save your card details for future reference and faster future payments. In such case, we may share your relevant personal information as necessary for the third parties to provide such services, including your name, residence, and email address. The processing of payments or authorization is solely in accordance with these third parties policies, terms and conditions and we are not in any manner responsible or liable to you or any third party for any delay or failure at their end in processing the payments. 
5.4. We may also share personal information if we believe it is necessary in order to investigate, prevent, or take action regarding illegal activities, suspected fraud, situations involving potential threats to the physical safety of any person, violations of various terms and conditions or our policies. 
5.5. We reserve the right to disclose your information when required to do so by law or regulation, or under any legal obligation or order under law or in response to a request from a law enforcement or governmental agency or judicial, quasi-judicial or any other statutory or constitutional authority or to establish or exercise our legal rights or defend against legal claims. 
5.6. You further agree that such disclosure, sharing and transfer of your personal information and non-personal information shall not cause any wrongful loss to you or to any third party, or any wrongful gain to us or to any third party. 
5.7. We and our affiliates will share / sell some or all of your personal information with another business entity should we (or our assets) plan to merge with, or be acquired by that business entity, or re-organization, amalgamation, restructuring of business. Should such a transaction occur that other business entity (or the new combined entity) will be required to follow this privacy policy with respect to your personal information. 
6. Retention of information 
6.1.We will put in place measures such that your personal or non-personal information, which is in our possession or under our control, is destroyed and/or anonymized as soon as it is reasonable to assume that (i) the purpose for which your personal or non-personal information were collected is no longer being served by the retention of such personal or non-personal information; and (ii) retention is no longer necessary for purpose required under applicable law. 
6.2. If you wish to cancel or deactivate your account, you may visit the “deactivate my account” section of the “my profile” page on the app. You would be prompted for sharing a reason for discontinuing services with us. Post this account would be deactivated. Or request that we no longer use your personal or non-personal information to provide you services. 
6.3. If you wish to delete your account and thereby discontinue using our service, you may do so at any time. We, however, reserve the right to retain, store and use your personal or non-personal information or content for our business purposes, whether such information or your account has been deleted or not. After a period of time, your data may be anonymized and aggregated, and then may be held by us as long as necessary for us to provide our services effectively, but our use of the anonymized data will be solely for analytic purposes. 
6.4. Please note that your withdrawal of consent or cancellation of your account may result in us not being able to provide you with our services or terminate any existing relationship that we may have with you. 
7. Link to other websites 
7.1. Our website may provide links to other sites. These links are provided for your convenience only and the provision of these links does not mean that sites are related or associated with us. Please note that these sites have their terms of use and privacy policies. You should check their privacy policy before you submit your personal information or any other data with them. We don’t guarantee the content and the security of those sites. 
7.2. We may have certain features on our website which may be hosted by third parties, your interaction with such features shall be governed by the privacy policy of such third parties. We shall not be responsible for any loss, damage, claim or expense caused as a result of you accessing these third-party sites and features. 
8. Security 
8.1. We strive to ensure the security, integrity, and privacy of your information and to protect your personal information against unauthorized access or unauthorized alteration, disclosure or destruction. We adopt adequate measures to prevent unauthorized access to your personal information. 
8.2. We reserve the right to conduct a security review at any time to verify your identity. You agree to provide us with all the information that we request for the security review. If you fail to comply with any security request, we reserve the right to terminate your account with us and prohibit your access to the website. 
8.3. We are not liable and cannot be held liable for any breach of security or for any actions of any third parties that receive your personal information. 
8.4. The trademarks, logos and service marks displayed on the website (“marks”) are the property of Pikkro or their merchants or respective third parties. You are not permitted to use the marks without the prior consent of Pikkro, the merchants or the third party that may own the marks. 
8.5. Notwithstanding anything contained in this policy or elsewhere, we shall not be held responsible for any loss, damage, or misuse of your personal information, if such loss, damage, or misuse is attributable to a force majeure event (as defined below). A “force majeure event” shall mean any event that is beyond our reasonable control and shall include, without limitation, sabotage, fire, flood, explosion, acts of God, civil commotion, strikes or industrial action of any kind, riots, insurrection, war, acts of government, computer hacking, unauthorized access to computer data and storage device, computer crashes, breach of security and encryption, etc. 
9. Choice/opt-out 
You agree and acknowledge that you are providing your information out of your free will. You have an option not to provide or permit Pikkro to collect your personal information or later on withdraw your consent with respect to such personal information so provided herein by sending an email to the grievance officer or such other electronic address as may be notified to you. 
10. Updates to this privacy policy 
Pikkro may change the data privacy practices and update this privacy policy as and when the need arises, and the same will be made available on the website. But our commitment to protect the privacy of website users will continue to remain. We suggest that you regularly check this privacy policy to apprise yourself of any updates. Your continued use of the website or provision of data or information thereafter will imply your unconditional acceptance of such updates to this privacy policy. 
11. Casual Visitors Note
No sensitive personal data or information is automatically collected by Pikkro from any casual visitors, who are merely perusing the Platforms.
Nevertheless, certain provisions of this Privacy Policy are applicable to even such casual visitors, and such casual visitors are also required to read and understand the privacy statements set out herein, failing which they are required to leave the Website or Application immediately.
You are not a casual visitor if you have willingly submitted any personal data or information to Pikkro through any means, including email, post or through the registration process on the Website or Application or indirectly through any merchant, vendor, or other User of Pikkro who have collected and provided your personal data with your consent. All such visitors will be deemed to be, and will be treated as, Users for the purposes of this Privacy Policy, and in which case, all the statements in this Privacy Policy apply to such people.
12. Grievance Officer
12.1. In accordance with Information Technology Act, 2000 and rules made thereunder, Consumer Protection Act 2019 and Consumer Protection (E-Commerce) Rules, 2020, the name, contact details and designation of the Grievance Officer are provided below:
Name: 
Designation: Grievance Officer
Email: 
Contact Number: 
Timings: within 48 hours of the issue's receipt and redress the same within 1 month of the date of receipt of the grievance.
12.2. In the event of any complaint or any issue raised by the User, the same shall be acknowledged and redressed by the Grievance Officer within the timelines specified under applicable laws.
12.3. All words and expressions used herein and not defined, but defined in the Information Technology Act, 2000 and/or the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011 shall have the meanings respectively assigned to them thereunder.




      </p>
    </div>
  )
}

export default RiderTermsAndConditions
