import React from 'react';

function Terms() {
  return (
    <div className="container max-w-lg mx-auto p-4">
      <p className='text-black'>
        <span className="block font-bold">Terms of Use</span>
        <span className="block">These terms of use is an electronic record in the form of an electronic contract formed under the Information Technology Act, 2000 and the rules made thereunder and the amended provisions pertaining to electronic documents / records in various statutes as amended by the Information Technology Act, 2000. These terms of use do not require any physical, electronic or digital signature.</span>
        <span className="block">This document is published and shall be construed in accordance with the provisions of rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 prescribed under Information Technology Act, 2000 that require publishing the rules and regulations, privacy policy and user agreement for access or usage of the website.</span>
        <span className="block">These terms of use is a legally binding document between Pikkro and user (both terms defined below). These terms of use will be effective upon your acceptance of the same (directly or indirectly in electronic form or by means of an electronic record) and will govern the relationship between Pikkro and user for the use of the website (defined below).</span>
        <span className="block">Please read these terms of use carefully. By using the website, you indicate that you understand, agree and consent to these terms of use. If you do not agree with the terms of these terms of use, please do not use this website. You hereby provide your unconditional consent or agreements to Pikkro as provided under section 43a and section 72a of Information Technology Act, 2000.</span>
        <span className="block">These terms of use of the website located at the url https://www.pikkro.in/ , mobile sites or mobile application (“website”) is between Pikkro Same Day Courier Services (“Pikkro” or “we” or “us” or “our"), a proprietorship firm having its office 114,Street no 16, Wazirabad village, Delhi-110084 , India and the guest users or registered users of the website ("you" or "your" or "yourself" or "user") describe the terms on which Pikkro offers you access to the website and such other services as are incidental and ancillary thereto ("services").</span>
        <span className="block">These terms of use is a contract between you and Pikkro. These terms of use shall be read together with the privacy policy or other terms and condition with all other notices, disclaimers, guidelines appearing on the website from time to time (collectively referred to as "agreement(s)") constitute the entire agreement upon which you are allowed to access and use the website and avail the services.</span>
        <span className="block">1) Interpretation</span>
        <span className="block">A) any reference to the singular includes a reference to the plural and vice versa, unless explicitly provided for otherwise; and any reference to the masculine includes a reference to the feminine and vice versa.</span>
        <span className="block">B) headings and captions are used for convenience only and will not affect the interpretation of these terms of use.</span>
        <span className="block">C) any reference to a natural person will, unless repugnant to the context, include his heirs, executors and permitted assignees. Similarly, any reference to a juristic person such as Pikkro will, unless repugnant to the context, include its affiliates, successors and permitted assignees.</span>
        <span className="block">2) Eligibility</span>
        <span className="block">A) only users who are 18 years of age or older may use the services. If you are under 18 years of age and you wish to download, install, access or use the services, your parents or legal guardian must acknowledge and agree to the terms of use. Should your parents or legal guardian fail to agree or acknowledge the terms of use, you shall immediately discontinue its use.</span>
        <span className="block">B) Pikkro reserves the right to refuse access to use the services offered if it is brought to Pikkro's notice or if it is discovered that you are under the age of 18 years.</span>
        <span className="block">3) Account registration and security</span>
        <span className="block">A) you may access and use the website and the services either as a registered user or as a guest user. However, not all sections of the website and services will be accessible to guest users.</span>
        <span className="block">B) Registered users: Pikkro makes certain sections of the services available to you through the website only if you have provided Pikkro certain required user information and created an account and a Pikkro id through certain log-in id and password ("account"). In the event you register as a user by creating an account in order to avail of the services provided by the website, you will be responsible for maintaining the confidentiality and security of the account, and are fully responsible for all activities that occur under your account. You agree to (a) immediately notify Pikkro of any unauthorized use of your account information or any other breach of security, and (b) ensure that you exit from your account at the end of each session. Pikkro cannot and will not be liable for any loss or damage arising from your failure To comply with this section. You may be held liable for losses incurred by Pikkro or any other user of or visitor to the website due to authorized or unauthorized use of your account as a result of your failure in keeping your account information secure and confidential. You shall ensure that the account information provided by you in the website's registration form is complete, accurate and up to date. Use of another user's account information for availing the services is expressly prohibited. If you provide any information that is untrue, inaccurate, not current or incomplete (or becomes untrue, inaccurate, not current or incomplete), or Pikkro has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, Pikkro has the right to suspend or terminate your account and refuse any and all current or future use of the website / services (or any portion thereof).</span>
        <span className="block">C) guest users: the website also allows limited access to the services for unregistered users (also called 'guest users'). Such users will be able to browse the website.</span>
        <span className="block">4) Services</span>
        <span className="block">A) Pikkro is an online platform inter-alia engaged in the business of providing an on-demand diversified delivery services, cash pickup services and other similar services through its website.</span>
        <span className="block">B) neither Pikkro own, sell, resell, furnish, provide, prepare any product nor manage and/or control the users.</span>
        <span className="block">C) Pikkro responsibility is limited to facilitating the delivery services.</span>
        <span className="block">5) Use of the website / services</span>
        <span className="block">You agree and undertake that when using a website / service, you will not:</span>
        <span className="block">A) defame, abuse, harass, stalk, threaten or otherwise violate the legal rights of others;</span>
        <span className="block">B) publish, post, upload, distribute or disseminate any inappropriate, profane, defamatory, infringing, obscene, indecent or unlawful topic, name, material or information;</span>
        <span className="block">C) conduct or forward surveys, contests, pyramid schemes or chain letters;</span>
        <span className="block">D) falsify or delete any author attributions, legal or other proper notices or proprietary designations or labels of the origin or source of software or other material contained in a file that is uploaded;</span>
        <span className="block">E) any information provided by you on this site shall not be misleading in any way;</span>
        <span className="block">F) use any deep-link, robot, spider or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the website or content, or in any way reproduce or circumvent the navigational structure or presentation of the website, to obtain or attempt to obtain any Materials, documents or information through any means not specifically made available through the website;</span>
        <span className="block">G) reverse engineer, modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer, or sell any information or software obtained from the website.</span>
        <span className="block">6) Third party contents</span>
        <span className="block">A) we cannot and will not assure that other users are or will be complying with the foregoing rules or any other provisions of these terms of use, and, as between you and us, you hereby assume all risk of harm or injury resulting from any such lack of compliance.</span>
        <span className="block">B) you acknowledge that when you access a link that leaves the services, the site you will enter into is not controlled by us and different terms of use and privacy policy may apply. By assessing links to other sites, you acknowledge that we are not responsible for those sites. We reserve the right to disable links to and / or from third-party sites to the services, although we are under no obligation to do so.</span>
        <span className="block">7) Promotions, discounts and coupons</span>
        <span className="block">Pikkro reserves the right to offer the discounts/promotional offers to any users of its own choice and shall not be held liable to any user for not offering the same. The discounts/offers have been made available at the sole discretion of Pikkro and are subject to change / amendment / modification from time to time. Pikkro at its sole discretion may at any time discontinue the discounts/offers without assigning any reasons or without any prior intimation whatsoever. The participation in discounts/offers is entirely voluntary and it is understood, that the participation by the user shall be deemed to have been made on a voluntary basis.</span>
        <span className="block">8) Communications</span>
        <span className="block">When you use the website or send emails or other data, information or communication to us, you agree and understand that you are communicating with us through electronic records and you consent to receive communications via electronic records from us periodically and as and when required. We may communicate with you by email or by such other mode of communication, electronic or otherwise.</span>
        <span className="block">9) Right to use logos</span>
        <span className="block">Nothing contained in these terms of use constitutes a license in favor of the user to use trademarks, service marks or logos and/or any other marks, owned by Pikkro that may be Reflected on the website ("ipr"). Any use by user of ipr will be only with the prior written permission from us. You acknowledge that we are the sole and exclusive owyner of our respective ipr’s and agree that you will not contest the ownership of the said ipr’s for any reason whatsoever.</span>
        <span className="block">10) No warranties</span>
        <span className="block">The website and the services are provided on an "as is" basis. We do not make any other representations or warranties of any kind, express or implied, including without limitation that the website or the services will meet your requirements, will always be available, accessible, uninterrupted, timely, secure, or operate without error.</span>
        <span className="block">11) Indemnity</span>
        <span className="block">You shall indemnify and hold harmless Pikkro, its owner, licensee, affiliates (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys' fees, made by any third party or penalty imposed due to or arising out of your breach of these terms of use, privacy policy and other terms and conditions, or your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.</span>
        <span className="block">12) Limitation of liability</span>
        <span className="block">In no event shall Pikkro be liable for any special, incidental, indirect or consequential damages of any kind in connection with these terms of use, even if user has been informed in advance of the possibility of such damages.</span>
        <span className="block">13) Updates</span>
        <span className="block">We reserve the right, at our sole discretion, to change, modify, add or remove portions of these terms of use, at any time without any prior written notice to you. We suggest that you regularly check these terms of use to apprise yourself of any updates. Your continued use of the website following the posting of changes will mean that you accept and agree to the revisions. As long as you comply with these terms of use, we grant you a personal, non-exclusive, non-transferable, limited privilege to enter and use the website.</span>
        <span className="block">14) Severability</span>
        <span className="block">If any of these terms should be determined to be illegal, invalid or otherwise unenforceable by reason of the laws of any state in which these terms are intended to be effective, then to the extent and within the jurisdiction which that term is illegal, invalid or unenforceable, it shall be severed and deleted and the remaining terms of use shall survive, remain in full force and effect and continue to be binding and enforceable.</span>
        <span className="block">15) Non-assignment</span>
        <span className="block">You shall not assign or transfer or purport to assign or transfer the contract between you and us to any other person.</span>
        <span className="block">16) Governing law, jurisdiction, and dispute resolution</span>
        <span className="block">These terms of use are governed by the laws of India. Any dispute arising under these terms of use shall be subject to the exclusive jurisdiction of the courts in Delhi, India.</span>
        <span className="block">17) Updates</span>
        <span className="block">We reserve the right, at our sole discretion, to change, modify, add or remove portions of these terms of use, at any time without any prior written notice to you. We suggest that you regularly check these terms of use to apprise yourself of any updates. Your continued use of the website following the posting of changes will mean that you accept and agree to the revisions. As long as you comply with these terms of use, we grant you a personal, non-exclusive, non-transferable, limited privilege to enter and use the website.</span>
        <span className="block">18) Severability</span>
        <span className="block">If any of these terms should be determined to be illegal, invalid or otherwise unenforceable by reason of the laws of any state in which these terms are intended to be effective, then to the extent and within the jurisdiction which that term is illegal, invalid or unenforceable, it shall be severed and deleted and the remaining terms of use shall survive, remain in full force and effect and continue to be binding and enforceable.</span>
        <span className="block">19) Non-assignment</span>
        <span className="block">You shall not assign or transfer or purport to assign or transfer the contract between you and us to any other person.</span>
        <span className="block">20) Governing law, jurisdiction, and dispute resolution</span>
        <span className="block">These terms of use are governed by the laws of India. Any dispute arising under these terms of use shall be subject to the exclusive jurisdiction of the courts in Delhi, India.</span>
      </p>
    </div>
  );
}

export default Terms;
