const mongoose=require("mongoose");

const orderSchema=mongoose.Schema({
    
    userPhone:{
        type:String,
        required:true
    },
     RiderPhone:{
      type:String,
      default:null
     },
     RiderName:{
      type:String,
      default:null
     }, 
     Item:{
        type:String,
        required:true
      },
      weight:{
          type:String,
          required:true
      },
      parcelValue:{
        type:Number,
        require:true
      },
      price:{
        type:Number,
        required:true
      },
      paymentType:{
        type:String,
        required:true
      },
      PickupDetails:{
        address:
        {
            type:String,
            required:true
        },
        Phone:{
            type:String,
            required:true
        },
        Locality:{
            type:String,
            required:true
        }
      }
      ,
      DeliveryDetails:{
        address:
        {
            type:String,
            required:true
        },
        Phone:{
            type:String,
            required:true
        },
        Locality:{
            type:String,
            required:true
        }
     },
     instruction:{
        type:String,
     },
     Date:{
        type:String,
        required:true
     },
     Time:{
        hours:{
         type:Number,
         required:true
        }, 
        minutes:{
         type:Number,
         required:true
        },
        meridian:{
         type:String,
         required:true
        }
     },
     accepted:{
       type:Boolean,
       default:false
     },
     picked:{
      type:Boolean,
      default:false
     },
     completed:{
        type:Boolean,
        default:false
     },
     canceled:{
        type:Boolean,
        default:false
     }
    },
    {
        timestamps:true
    }
)

const orderModel=mongoose.model("orders",orderSchema);
module.exports = orderModel